const FETCH_PRODUCTS = 'FETCH_PRODUCTS',
      FETCHED_PRODUCTS = 'FETCHED_PRODUCTS',
      FETCH_PRODUCTS_ERRORED = 'FETCH_PRODUCTS_ERRORED';

export {
    FETCH_PRODUCTS,
    FETCHED_PRODUCTS,
    FETCH_PRODUCTS_ERRORED
};