export const LOADING = 'LOADING';
export const FETCHING_PRODUCTS = 'FETCHING_PRODUCTS';
export const FETCHED_PRODUCTS = 'FETCHED_PRODUCTS';
export const FETCH_PRODUCTS_ERRORED = 'FETCH_PRODUCTS_ERRORED';
export const LOADING_REVIEWS = 'LOADING_REVIEWS';
export const FETCHING_REVIEWS = 'FETCHING_REVIEWS';
export const FETCHED_REVIEWS = 'FETCHED_REVIEWS';
export const FETCH_REVIEWS_ERRORED = 'FETCH_REVIEWS_ERRORED';
