export const LOADING = 'LOADING';
export const FETCHING_PRODUCTS = 'FETCHING_PRODUCTS';
export const FETCHED_PRODUCTS = 'FETCHED_PRODUCTS';
export const FETCH_PRODUCTS_ERRORED = 'FETCH_PRODUCTS_ERRORED';
export const FETCHING_PRODUCT = 'FETCHING_PRODUCT';
export const FETCHED_PRODUCT = 'FETCHED_PRODUCT';
export const FETCH_PRODUCT_ERRORED = 'FETCH_PRODUCT_ERRORED';
