export const LOADING = 'LOADING';
export const FETCHING_PRODUCTS = 'FETCHING_PRODUCTS';
export const FETCHED_PRODUCTS = 'FETCHED_PRODUCTS';
export const FETCH_PRODUCTS_ERRORED = 'FETCH_PRODUCTS_ERRORED';